@startuml
card 料金
    card 運賃
    card 特急料金
料金 --* 運賃
料金 --* 特急料金

card 乗車情報
    card 車両名
        card ひかり
        card のぞみ
    card 席
        card 指定席
        card 自由席
    card 季節
        card 通常期
        card 閑散期
        card 繁忙期
    card 移動情報
        card 出発駅
        card 停車駅
        card 移動距離
        card 移動区分
            card 片道
            card 往復
    card 乗車人数
        card 大人の乗車人数
        card 子供の乗車人数
    card 乗車日

乗車情報 --* 車両名
乗車情報 --* 席
乗車情報 --* 季節
乗車情報 --* 移動情報
乗車情報 --* 乗車人数
乗車情報 --* 乗車日
車両名 <|-- ひかり
車両名 <|-- のぞみ
席 <|-- 指定席
席 <|-- 自由席
季節 <|-- 通常期
季節 <|-- 閑散期
季節 <|-- 繁忙期
移動情報 --* 出発駅
移動情報 --* 停車駅
移動情報 --* 移動距離
移動情報 --* 移動区分
移動区分 <|-- 片道
移動区分 <|-- 往復
乗車人数 --* 大人の乗車人数
乗車人数 --* 子供の乗車人数
@enduml

